# Generated by Django 5.0.6 on 2024-08-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eDiary', '0004_noteshistory_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('conveted_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
