# Generated by Django 5.0.6 on 2024-08-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eDiary', '0005_audiotext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioText',
        ),
        migrations.AddField(
            model_name='notes',
            name='diary_image',
            field=models.ImageField(blank=True, default='dell.png', upload_to=''),
        ),
    ]
